[tool.black]
line-length = 120
target-version = ['py36', 'py37']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
line_length=120
multi_line_output=3
include_trailing_comma=true
force-grid-wrap=0
combine_as_imports=true